import sys, json

try:
    with open(sys.argv[1], 'r') as f:
        data = json.load(f)
except Exception:
    sys.exit(0)

metrics = data.get("metrics", {})
# Handle both native k6 summary export AND custom summary generated by mock wrapper
if "metrics" not in data and "custom_metrics" in data:
    metrics = data.get("custom_metrics", {})
    # For custom_metrics from the mock summary, shape is slightly different
    # But usually k6 end-of-test summary has a "metrics" object
elif "metrics" not in data:
    # check if raw k6 export
    sys.exit(0)

# Extract APIs
apis = {}
for k, v in metrics.items():
    if k.startswith("duration_"):
        api = k.replace("duration_", "")
        if api not in apis: apis[api] = {}
        apis[api]['duration'] = v
    elif k.startswith("sample_"):
        api = k.replace("sample_", "")
        if api not in apis: apis[api] = {}
        apis[api]['sample'] = v
    elif k.startswith("error_rate_"):
        api = k.replace("error_rate_", "")
        if api not in apis: apis[api] = {}
        apis[api]['error_rate'] = v
    elif k.startswith("error_count_"):
        api = k.replace("error_count_", "")
        if api not in apis: apis[api] = {}
        apis[api]['error_count'] = v
    elif k.startswith("rps_"):
        api = k.replace("rps_", "")
        if api not in apis: apis[api] = {}
        apis[api]['rps'] = v

# Fallback to general metrics if no custom metrics
if not apis:
    if "http_req_duration" in metrics:
        apis["All_Requests"] = {
            "duration": metrics["http_req_duration"],
            "sample": {"values": {"count": metrics.get("http_reqs", {}).get("values", {}).get("count", 0)}},
            "error_rate": {"values": {"rate": metrics.get("http_req_failed", {}).get("values", {}).get("rate", 0)}},
            "error_count": {"values": {"passes": metrics.get("http_req_failed", {}).get("values", {}).get("passes", 0)}},
            "rps": {"values": {"rate": metrics.get("http_reqs", {}).get("values", {}).get("rate", 0)}}
        }

if not apis:
    sys.exit(0)

print("\n\033[1;36mK6 Load Test Summary\033[0m")
print(f"{'API':<50} | {'Samples':<8} | {'Avg(ms)':<8} | {'Max(ms)':<8} | {'Min(ms)':<8} | {'P95(ms)':<8} | {'Err(%)':<6} | {'RPS':<6} | {'Err_Samp':<8}")
print("-" * 135)

total_samples = 0
total_errors = 0
for api, m in sorted(apis.items()):
    if len(api) > 48:
        display_api = "..." + api[-45:]
    else:
        display_api = api

    dur = m.get('duration', {}).get('values', m.get('duration', {}))
    avg = dur.get('avg', 0) if isinstance(dur, dict) else 0
    mx = dur.get('max', 0) if isinstance(dur, dict) else 0
    mn = dur.get('min', 0) if isinstance(dur, dict) else 0
    p95 = dur.get('p(95)', dur.get('p95', 0)) if isinstance(dur, dict) else 0
    
    samp = m.get('sample', {}).get('values', m.get('sample', {}))
    samples = samp.get('count', 0) if isinstance(samp, dict) else samp
    total_samples += int(samples)
    
    err_r = m.get('error_rate', {}).get('values', m.get('error_rate', {}))
    erate = err_r.get('rate', 0) * 100 if isinstance(err_r, dict) else err_r * 100
    
    err_c = m.get('error_count', {}).get('values', m.get('error_count', {}))
    ecount = err_c.get('count', err_c.get('passes', 0)) if isinstance(err_c, dict) else err_c
    total_errors += int(ecount)
    
    rps_obj = m.get('rps', {}).get('values', m.get('rps', {}))
    rps = rps_obj.get('rate', 0) if isinstance(rps_obj, dict) else rps_obj

    print(f"{display_api:<50} | {int(samples):<8} | {float(avg):<8.2f} | {float(mx):<8.2f} | {float(mn):<8.2f} | {float(p95):<8.2f} | {float(erate):<6.2f} | {float(rps):<6.2f} | {int(ecount):<8}")

print("-" * 135)
print(f"{'TOTAL':<50} | {total_samples:<8} | {'-':<8} | {'-':<8} | {'-':<8} | {'-':<8} | {'-':<6} | {'-':<6} | {total_errors:<8}")
print("")
